name: note_app
description: App Note

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  shared_preferences: ^2.1.2
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^5.0.5

  flutter_switch: ^0.3.2
  hooks_riverpod: ^2.3.6
  equatable: ^2.0.5

  dots_indicator: ^2.0.0
  image_picker: ^0.8.7
  permission_handler: ^10.2.0
  country_picker: ^2.0.7
  pinput: ^2.2.20

  flutter_staggered_grid_view: ^0.6.2

  intl: any

  freezed_annotation: 2.2.0
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  analyzer: ^5.13.0

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
